### ISSUE TITLE
5. Expose isolated diagnostics for Core-defined provider contracts

### ISSUE THREAD

**Issue by muffledcry** [Paper-Data-Suite/pds-core#189]
## Suggested branch 
189-core-provider-diagnostics

Part of #178.

## Suggested branch

```text
189-core-provider-diagnostics
```

# Summary

Add a bounded, failure-isolating diagnostic surface for **Core-defined provider entry points** without weakening the existing strict runtime registry behavior.

The concrete consumer is suite `pds doctor`, but the API belongs in Core because Core owns the provider contracts being inspected.

Initial scope is limited to:

```text
paper_data_suite.modules
paper_data_suite.publication_producers
```

These are respectively Core's routing-module and publication-producer provider contracts.

Do not turn this issue into generic application discovery.

---

# Existing behavior to preserve

Core already exposes strict runtime discovery/registry construction for routing profiles and publication-producer profiles.

Those runtime paths intentionally fail closed when a trustworthy registry cannot be constructed.

Examples include:

```text
entry-point load failure
loaded object is not callable
provider raises
provider returns invalid object
profile identity mismatch
duplicate/conflicting provider identity
Core contract incompatibility
```

That fail-closed behavior is correct for runtime routing/publication work.

Do not weaken it so that a health-check command can continue.

Instead, create a separate diagnostic surface.

---

# Ownership boundary

The suite already owns:

```text
supported component list
exact package versions
distribution names
wheel identities/hashes
console-script expectations
launchability
suite qualification
Python qualification
external prerequisites
release composition
```

Those come from the suite compatibility manifest and installed distribution metadata.

Core MUST NOT duplicate them.

Core owns:

```text
what a routing provider contract means
what a publication-producer provider contract means
how the returned Core profile is validated
Core compatibility semantics
duplicate Core provider identity
```

This issue diagnoses those Core-owned contracts only.

---

# Two explicit diagnostic depths

Do not hide materially different behavior behind one ambiguous `discover` operation.

Provide or clearly distinguish:

## Metadata inspection

This level MUST NOT load optional provider code.

It should enumerate candidate entry-point metadata in deterministic order and expose bounded metadata such as:

```text
entry-point group
entry-point name
entry-point target/value
owning distribution, when determinable safely
```

It requires no workspace.

It executes no provider.

## Provider validation

This level is explicit permission to:

```text
load entry-point object
verify callable requirement
call zero-argument profile provider
validate returned Core profile
evaluate applicable Core compatibility
detect identity mismatch
detect duplicate/conflicting Core identity
```

Each candidate must produce an independent bounded diagnostic outcome where safe.

One malformed optional provider must not prevent diagnostic results for unrelated providers.

---

# Diagnostic result model

Use typed immutable results.

Exact public names may follow existing Core conventions, but each candidate should be able to represent, at minimum:

```text
provider kind / entry-point group
entry-point name
entry-point target
owning distribution when available
diagnostic stage reached
load attempted
load outcome
provider call attempted
provider call outcome
returned declared identity when safely available
profile validation outcome
Core compatibility outcome
duplicate/conflict outcome
stable diagnostic code
bounded safe message
validated profile on success, if appropriate
```

A useful stage vocabulary may distinguish:

```text
metadata
load
call
profile_validation
identity_validation
compatibility
registry_conflict
valid
```

Do not expose raw tracebacks as the normal public result.

Do not include arbitrary environment dumps.

---

# Required independent outcomes

The diagnostic API must be capable of distinguishing cases equivalent to:

```text
no candidates installed
candidate metadata present
entry-point load failure
loaded object not callable
provider invocation failure
invalid returned profile
provider/profile identity mismatch
unsupported Core contract version
duplicate/conflicting provider identity
valid compatible provider
```

If Python/importlib metadata cannot determine an owning distribution reliably for a particular candidate, represent that fact honestly rather than guessing.

---

# Runtime registry behavior

Existing runtime functions such as:

```text
discover_module_profiles(...)
build_module_registry(...)
discover_publication_producer_profiles(...)
build_publication_producer_registry(...)
```

must retain their current strict semantics unless an additive internal refactor preserves equivalent behavior exactly.

The new health-diagnostic surface is not a replacement registry.

Do not return a partially trusted routing registry and call it valid merely because diagnostics are failure-isolating.

---

# No-workspace guarantee

Provider metadata and profile-contract diagnostics in this issue must not require a PDS workspace.

Do not:

```text
resolve a workspace
read a roster
read student evidence
read module work roots
read Publication Records
read scans
```

merely to determine whether installed provider metadata/code satisfies a Core-defined provider contract.

A provider contract that is specified as zero-argument metadata must remain so.

---

# Import safety

Metadata-only inspection must not import optional applications.

Provider validation may import/call provider code only because the caller explicitly requested the deeper diagnostic.

Core package import itself must remain side-effect free.

Do not import ScoreForm, Quillan, Concord, Meridian, Vitrine, or Portia by hard-coded package name.

Entry points remain the integration mechanism.

---

# Duplicate handling

Diagnostics must report duplicates/conflicts without erasing the individual candidate observations that produced the conflict.

For example, if two entry points both claim the same Core provider identity, the caller should be able to see:

```text
candidate A
candidate B
conflicting identity
```

rather than receiving only one aggregate exception.

The strict runtime registry should continue to reject the conflict.

---

# Relationship to #191

#191 introduces a separate Core-defined module-operations provider family.

Do not preempt its contract here.

Design reusable diagnostic machinery where sensible, but do not make #189 depend on a guessed #191 profile shape.

After #191 exists, its provider diagnostics may reuse the same bounded principles.

---

# `pds doctor`

`pds doctor` is a consumer, not the owner of this result model.

The suite remains responsible for mapping Core diagnostic outcomes to:

```text
PASS
WARN
FAIL
SKIP
```

and for teacher-facing remediation.

Core should not import suite doctor types or encode doctor presentation policy.

`pds doctor` is not hard-blocked on this issue; older Core contracts may be represented honestly with reduced diagnostic fidelity.

---

# Tests

Use synthetic entry points/providers.

Cover at least:

```text
no candidates
one valid routing provider
one valid publication provider
metadata inspection does not load provider
load failure
non-callable loaded object
provider raises
invalid profile
identity mismatch
Core compatibility failure
duplicate identity
valid provider beside broken provider
deterministic candidate ordering
runtime strict registry still fails closed
diagnostic path does not require workspace
safe bounded errors without traceback leakage
```

Do not require released sibling applications to be installed for Core's unit tests.

---

# Documentation

Document clearly:

```text
metadata inspection vs provider execution
runtime strict registry vs diagnostic inventory
failure isolation
workspace independence
import behavior
privacy limits
suite-vs-Core ownership
```

Update the existing routing/publication compatibility documentation rather than creating contradictory provider terminology.

---

# Explicit non-goals

This issue does not implement:

```text
generic PDS application discovery
suite release qualification
package version policy
launchability
console-script launch
module readiness
module attention
module diagnostics that require private storage
doctor statuses/remediation
workspace diagnostics
package installation
provider repair
automatic disabling of bad providers
```

---

# Acceptance criteria

This issue is complete when:

- Core can enumerate routing/publication provider entry-point metadata without loading optional provider code;
- callers can explicitly request isolated provider load/call/profile validation;
- each independent candidate receives a bounded typed outcome;
- one broken candidate does not hide unrelated diagnostic results;
- duplicate/conflicting provider identities remain visible diagnostically;
- strict runtime registries remain fail-closed;
- no workspace is required;
- no sibling package names are hard-coded;
- generic suite component/version/launchability authority remains outside Core;
- tests cover malformed, conflicting, compatible, and mixed candidate sets; and
- the full Core validation suite passes.
